language: ruby

before_install:
  - bundle config without 'development'

install: bundle install
script: bundle exec rake

branches:
  only:
    - master

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  include:
    - rvm: 2.6.3
    - rvm: 2.5.5
    - rvm: 2.4.6
    - rvm: ruby-head
    - rvm: rbx-2
