dist: xenial
language: ruby

before_install:
  - bundle config without 'development'

install: bundle install
script: bundle exec rake

branches:
  only:
    - master

after_success:
  - '[ ${TRAVIS_EVENT_TYPE} != "pull_request" ] && [ ${TRAVIS_BRANCH} = "master" ] && bundle exec codeclimate-test-reporter'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  include:
    - rvm: 2.7.0
    - rvm: 2.6.5
    - rvm: 2.5.7
    - rvm: 2.4.9
    - rvm: ruby-head
    - rvm: rbx-2
